### ISSUE TITLE
document.getElementById(...).restore is not a function

### ISSUE THREAD

**Issue by stramel** [Polymer/test-fixture#21]
I am getting this when trying to test two `test-fixtures` in the same file but different `describe` blocks.

When I remove one of them, it works fine. I am not actually calling `restore` I am using WCT with Polymer

**Comment by bedeoverend** [comment]
I'm getting this one as well - pretty regularly, though it's intermittent. Looks like in [this line](https://github.com/Polymer/test-fixture/blob/master/test-fixture-mocha.js#L26). Perhaps should be doing a check for if element exists before restoring?

**Comment by ThilinaTCH** [comment]
Hi All,

We are also facing same kind of issue
`Test run ended in failure: Error thrown outside of test function: document.getElementById(...).restore is not a function`
This happens only on Chrome on dom=shadow scenario
They are passing on Chrome with dom=shady and both dom type for other browsers, Firefox, Safari, etc.

we are using Polymer 1.6 and web-component-tester latest, 5.0.1

**Comment by valdrinkoshi** [comment]
This is a regression on Chrome 57 https://bugs.chromium.org/p/chromium/issues/detail?id=701601
The GC might kick any time, multiple times, causing custom elements in the dom to loose their properties/methods. So far we couldn't find a good workaround for this, so we're suggesting to use M58 or M56 for the time being (until the fix makes it to stable).

**Comment by ThilinaTCH** [comment]
@valdrinkoshi Thanks!, and yes we could be able to get rid of this issue when testing with Chrome 56. So we have to upgrade polymer version when this bug has fixed in order to run tests with latest Chrome?
Currently we are using polymer 1.6, would it be OK to upgrade to latest polymer 1.x version?

**Comment by valdrinkoshi** [comment]
@ThilinaTCH you can configure WCT to run with chrome beta instead of stable https://github.com/Polymer/web-component-tester#configuration

**Comment by ThilinaTCH** [comment]
@valdrinkoshi Ah OK sure will do it for now. Thanks!

**Comment by stramel** [comment]
Closing this since stable is now Chrome 58
