### ISSUE TITLE
Leaky state

### ISSUE THREAD

**Issue by nicholaswmin** [Polymer/test-fixture#22]
It seems that `test-fixture` doesn't really reset all types of properties of the element between calls.

For example I have an `Array: items` which I push to just once in each test and on subsequent tests, the item I pushed still seems to exist in `Array: items`, even though `Array: items` should be empty since calling `fixture()` should give me brand new element

Leaky state or am I missing something? 

I've wrote lots of `wct` tests so far and this is the first time I see this. Note that I'm talking about 1.x releases of this.

## Steps to reproduce 

- Create a new seed element using `$ polymer init`
- Add an Array called `items` as a property to the element
- Write 2 identical `test()`s where in each test: 
  - push something into the  `Array: items`, **once in each test**. 
  - assert that on the end of each test, the `Array: items` **has only one item**
- Run the tests, using `$ wct`, or using the browser runner.

## Expected Results

- At the end of each test, the element should have only 1 element in the `items` Array.
- `test-fixture` resets the element each time, so the next test starts with an empty `items` Array
- Both test should pass

## Actual Results

- At the end of 2nd test, the element has 2 items in it's `items` Array.
- The `test-fixture` did not really 'reset' the element, `Array: items` since to contain the previous test's pushed item.
- Therefore the 2nd test fails

### my-element.html

```html
<dom-module id="my-element">
  <template></template>

  <script>
    Polymer({

      is: 'my-element',

      properties: {
        items: {
          type: Array,
          value: []
        },
      }

    });
  </script>
</dom-module>
```
### my-element_test.html

```html
<test-fixture id="basic">
  <template>
    <my-element></my-element>
  </template>
</test-fixture>

<script>
  suite('fixture-test', function() {
    test('Items should have 1 item when pushing 1 item', function() {
      var element = fixture('basic');
      element.push("items", 1);
      assert.equal(element.items.length, 1);
    });
   
   // Fails with message: 
   // expected 2 to equal 1
    test('Items should have 1 item when pushing 1 item', function() {
      var element = fixture('basic');
      element.push("items", 1);
      assert.equal(element.items.length, 1);
    });

  });
</script>
```

**Comment by notwaldorf** [comment]
I think this is because if you create `items` as a static array like that, it's actually created on the class, not on the instance. It should be `value: function() { return []; }` (see https://www.polymer-project.org/1.0/docs/devguide/properties#configure-values)

/cc @arthurevans to double check I'm not making this up

**Comment by nicholaswmin** [comment]
Ty, I'll give it a test drive now.

**Comment by nicholaswmin** [comment]
Working. Thanks a lot.
